"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const verifyJwt_1 = require("../Middlewares/verifyJwt");
const categoryController_1 = require("../controllers/categoryController");
const router = (0, express_1.Router)();
router.post("/create", verifyJwt_1.verifyJwt, categoryController_1.createCategoryController);
router.put("/update/:id", verifyJwt_1.verifyJwt, categoryController_1.updateCategoryController);
router.get("/all", categoryController_1.getAllCategoriesController);
router.delete("/delete/:id", verifyJwt_1.verifyJwt, categoryController_1.deleteCategoryController);
exports.default = router;
